version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: edo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=securepassword
      - MONGO_INITDB_DATABASE=edodb
    command: --wiredTigerCacheSizeGB 1 --logpath /dev/null
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - edo-network

  mongo-express:
    image: mongo-express:latest
    container_name: edo-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=securepassword
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - edo-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: edo-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://admin:securepassword@mongodb:27017/edodb?authSource=admin
      - JWT_SECRET=secure_jwt_secret_key_for_edo_app
      - JWT_EXPIRES_IN=7d
      - CORS_ORIGIN=http://localhost:5173
      - LOG_LEVEL=debug
    volumes:
      - ./server/src:/app/src
      - ./server/logs:/app/logs
      - /app/node_modules
    networks:
      - edo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edo-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000/api
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    networks:
      - edo-network

networks:
  edo-network:
    driver: bridge

volumes:
  mongodb_data:
