[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  BUN_VERSION = "1.0.26"

# Настройки для продакшен-окружения
[context.production.environment]
  VITE_API_URL = "https://api.edo-app.domain.com/api"
  NODE_ENV = "production"
  VITE_DEMO_MODE = "false"

# Настройки для превью-деплоя
[context.deploy-preview.environment]
  VITE_API_URL = "https://api-staging.edo-app.domain.com/api"
  NODE_ENV = "staging"
  VITE_DEMO_MODE = "false"

# Настройки для ветки разработки
[context.develop.environment]
  VITE_API_URL = "https://api-dev.edo-app.domain.com/api"
  NODE_ENV = "development"
  VITE_DEMO_MODE = "true"

# Настройки для API прокси в production
[[redirects]]
  from = "/api/*"
  to = "https://api.edo-app.domain.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Настройки для API прокси в staging
[[redirects]]
  from = "/api/*"
  to = "https://api-staging.edo-app.domain.com/api/:splat"
  status = 200
  force = true
  conditions = {Role = ["staging"]}
  headers = {X-From = "Netlify-Staging"}

# Настройки для API прокси в development
[[redirects]]
  from = "/api/*"
  to = "https://api-dev.edo-app.domain.com/api/:splat"
  status = 200
  force = true
  conditions = {Role = ["develop"]}
  headers = {X-From = "Netlify-Dev"}

# Кэширование статических ресурсов
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Кэширование шрифтов
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Настройки для SPA - должна быть последней
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Общие настройки заголовков безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://api.edo-app.domain.com https://api-staging.edo-app.domain.com https://api-dev.edo-app.domain.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[dev]
  command = "bun run dev"
  framework = "#custom"
  targetPort = 5173
  port = 8888
  publish = "dist"
  autoLaunch = true
